name: Generate Snake Contributions

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate and Push Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Generate Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: KapilPatil7 # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

